### PR TITLE
Insert Before Error Fix

### PR DESCRIPTION
**Pull request by Cattn**
Please refer to my post in #477 for more information on this.

TLDR: Not 100% sure if this is just a bandaid solution for a more niche problem, or this solves an issue preventing the emulator from loading sometimes

### CODE REVIEW

**Comment by ethanaobrien** [comment]
Before I merge this, I'm really confused why this would be happening. How are there no script tags on the page? How are you loading the scripts? Are you manually deleting any tags? I'm very confused about how this is happening. What browser are you using?

**Comment by Cattn** [comment]
> Before I merge this, I'm really confused why this would be happening. How are there no script tags on the page? How are you loading the scripts? Are you manually deleting any tags? I'm very confused about how this is happening. What browser are you using?

1. I'm really not sure how this happens, 
2. https://github.com/Math-Study/wii-gba/blob/main/launchpad.html happens here (it happened if I removed loadGame.js script, and just hard coded the link in normally as well.) it also happens to me on some of my other projects.
3. None of my scripts should be messing with tags, in the example above: https://github.com/Math-Study/wii-gba/blob/main/data/loadGame.js The JS file simply sets the values for game info.
4. I'm using Chrome V109 on Windows

I've had reports of this from some people using my sites, although it's been harder to track, and also seems to of popped up recently, I updated to the newest version of EmulatorJS a while ago so I don't think it's from that. I also don't think it's something I've done due to the reasons above

**Comment by Cattn** [comment]
I've tried investigating why it happens, but I'm pretty confused, what I can say is that a hard reload of the page usually will fix it immediately while a normal one may take a few tries

**Comment by Cattn** [comment]
To note* This solution I'm PR is implemented currently in the above linked repository

**Comment by ethanaobrien** [comment]
Could you send me a link to a page that has the broken version? I would like to see this error.

**Comment by Cattn** [comment]
> Could you send me a link to a page that has the broken version? I would like to see this error.

Yes, let me revert the changes one of my forks, and I'll send it, it's kinda like the freezing issue, it doesn't show up every time but it definitely is much more consistent

**Comment by Cattn** [comment]
1. https://cattn.github.io/gba/gba.html I just noticed it seems to happen when coming from another page : Scroll down, then just click one of the games and it should work
2. https://math-study.github.io/wii-gba/ Just click on the New Super Mario Bros tile, and then play 

I've noticed you also might need to reload a few times before it happens.

My current theory after looking at all of this seems to be it may be because somehow of the values being set when going to the page?

This is seeming more like something that I've kinda caused, but also doesn't seem like it's very uncommon of an issue, or specific as both sites use completely different systems

**Comment by ethanaobrien** [comment]
Would you mind updating the core files? I just pushed a change that should fix this. It turns out the insert before call wasnt even needed because the variables are still defined by the time we need them because of when the onload event fires.

**Comment by Cattn** [comment]
> Would you mind updating the core files? I just pushed a change that should fix this. It turns out the insert before call wasnt even needed because the variables are still defined by the time we need them because of when the onload event fires.

Will do, one moment

**Comment by Cattn** [comment]
I updated the Second Link

**Comment by Cattn** [comment]
Sorry, I meant I updated the first link I listed above

**Comment by Cattn** [comment]
Works without issue now, thanks!

**Comment by ethanaobrien** [comment]
Awesome! I'll go ahead and close the linked issue

**Comment by Cattn** [comment]
Gotcha

**Pull request closed without merging**
