### PR TITLE
Fix Localization

### LINKED ISSUE #586: [Bug] Translation problems
I notice that after 4.x versions, several label translations are not working (even when they have the same text on localization\language file.

### PR DESCRIPTION
**Pull request by allancoding**
## Fix Localization
- Add's the option `EJS_settingsLanguage` for debugging and adding new languages. - Set it to `true` and console logs will show the missing translations.
- Fixed all of the languages, some may need to be fix by people that will know the best translation.
- Fixed the Translation.html page so it works better.

I think all of the options are in `en.json` or `retroarch.json`
Fixes #586

### CODE REVIEW

**Comment by ethanaobrien** [comment]
Can we define `window.EJS_missingLang` on the `this` object. It can still be accessed through the `EJS_emulator` object

**Comment by ethanaobrien** [comment]
And why isn't logging available for all localization calls? Shouldn't this be checked in the function itself rather than passed to it?

**Comment by allancoding** [comment]
I will fix this tomorrow.

**Comment by zmarteline** [comment]
Nice job, I am rebilding the pt-br translation file for all labels (using the correct sequency they show in debug log). I will upload the result file today in my original issue request.

**Comment by allancoding** [comment]
They do not need to be in the correct sequence

**Comment by zmarteline** [comment]
> They do not need to be in the correct sequence
I wish my obsessive behavior also believe that! Lmao

**Comment by zmarteline** [comment]
[pt-BR.json.txt](https://github.com/EmulatorJS/EmulatorJS/files/12327778/pt-BR.json.txt)
Ok, PT-BR is done for all genesis, master system, 32x, Sega cd, Atari 2600, 3DO and PSX labels. I just need instructions on how to insert special chars, to fix that kind of glitch:

z

**Comment by ethanaobrien** [comment]
@allancoding can you add a "translator"

Basically, any characters listed here (https://www.whatsmyip.org/html-characters/) should be replaced how it shows here (https://stackoverflow.com/questions/56688899/accented-letter-and-quotation-marks-in-html-innertext). Japanese, Chinese etc are not special characters

**Comment by ethanaobrien** [comment]
@allancoding can you add a "translator"

Basically, any characters listed here (https://www.whatsmyip.org/html-characters/) should be replaced how it shows here (https://stackoverflow.com/questions/56688899/accented-letter-and-quotation-marks-in-html-innertext). Japanese, Chinese etc are not special characters

**Comment by ethanaobrien** [comment]
Nevermind @allancoding 

@zmarteline What browser are you using, what OS? It looks like you just dont have the fonts installed, as it works on my computer™

**Comment by allancoding** [comment]
@zmarteline  You should just be able to copy and paste the special character into the json. that's what I did

**Comment by ethanaobrien** [comment]
Typing the character shouldn't make a difference

**Comment by zmarteline** [comment]
Chrome.
also tried `&#231` and  `&ccedil`  for ç, but did not work.

**Comment by ethanaobrien** [comment]
According to the javascript console, its definitely a user issue
image

**Comment by ethanaobrien** [comment]
Possibly because of what you have the encoding set to

**Comment by zmarteline** [comment]
> @zmarteline You should just be able to copy and paste the special character into the json. that's what I did

I did that. you can see im my json (Accents in the words).

**Comment by ethanaobrien** [comment]
@zmarteline The issue is the files encoding. Your file is ANSI, but UTF-8 is expected

**Comment by zmarteline** [comment]
{
"Restart": "Restart",
"Pause": "Pausar",
"Play": "Jogar",
"Save State": "Armazenar Save State",
"Load State": "Carregar Save State",
"Control Settings": "Configurações do Controle",
"Cheats": "Trapaças",
"Cache Manager": "Gerenciador de cache",
"Export Save File": "Salvar Estado em arquivo",
"Import Save File": "Carregar Estado de arquivo",
"Netplay": "Netplay",
"Mute": "Mudo",
"Unmute": "Desmutar",
"Settings": "Ajustes",
"Enter Fullscreen": "Tela cheia",
"Exit Fullscreen": "Sair da tela cheia",
"Reset": "Resetar",
"Clear": "Limpar",
"Close": "Fechar",
"QUICK SAVE STATE": "SALVAR ESTADO RÁPIDO",
"QUICK LOAD STATE": "CARREGAR ESTADO RÁPIDO",
"CHANGE STATE SLOT": "TROCAR SLOT DO ESTADO",
"FAST FORWARD": "AVANÇO RÁPIDO",
"SLOW MOTION": "CAMERA LENTA",
"REWIND": "RETROCEDER",
"Player": "Jogador",
"Connected Gamepad": "Controle conectado",
"Gamepad": "Controle",
"Keyboard": "Teclado",
"Set": "Definir",
"Add Cheat": "Adicionar Trapaça",
"Create a Room": "Criar uma Sala",
"Rooms": "Salas",
"Loading...": "Carregando",
"Download Game Core": "Carregando emulador do videogame",
"Decompress Game Core": "Descompactando emulador do videogame",
"Download Game Data": "Carregando dados do jogo",
"Decompress Game Data": "Descompactando dados do jogo",
"Shaders": "Sombreamento",
"Disabled": "Desativado",
"2xScaleHQ": "2xScaleHQ",
"4xScaleHQ": "4xScaleHQ",
"CRT easymode": "CRT easymode",
"CRT aperture": "CRT aperture",
"CRT geom": "CRT geom",
"CRT mattias": "CRT mattias",
"FPS": "FPS",
"show": "mostrar",
"hide": "ocultar",
"Fast Forward Ratio": "Taxa de avanço rápido",
"Slow Motion Ratio": "Taxa de camera lenta",
"Fast Forward": "Avanço rápido",
"FPS": "FPS",
"Enabled": "Ativado",
"Slow Motion": "Camera lenta",
"Rewind Enabled (requires restart)": "Camera lenta ativada(Necessário reiniciar)",
"Rewind Granularity": "Granularidade do retrocesso",
"Save State Slot": "Slot do Save State",
"Save State Location": "Local do Save State",
"Download": "Download",
"Keep in Browser": "Manter no Browser",
"Virtual Gamepad": "Controle virtual",
"Left Handed Mode": "Modo canhoto",
"genesis plus gx frameskip threshold": "genesis plus gx - limite de pulo de quadros",
"genesis plus gx lowpass range": "genesis plus gx - alcance do passa-baixa",
"genesis plus gx psg preamp": "genesis plus gx - psg pré-amplificador",
"genesis plus gx fm preamp": "genesis plus gx -  pré-amplificador fm",
"genesis plus gx cdda volume": "genesis plus gx - cdda volume",
"genesis plus gx pcm volume": "genesis plus gx - pcm volume",
"genesis plus gx audio eq low": "genesis plus gx - eq áudio baixo",
"genesis plus gx audio eq mid": "genesis plus gx - eq áudio medio",
"genesis plus gx audio eq high": "genesis plus gx - eq áudio alto",
"genesis plus gx enhanced vscroll limit": "genesis plus gx - limite de rolagem vertical aprimorada",
"genesis plus gx psg channel 0 volume": "genesis plus gx - psg channel 0 volume",
"genesis plus gx psg channel 1 volume": "genesis plus gx - psg channel 1 volume",
"genesis plus gx psg channel 2 volume": "genesis plus gx - psg channel 2 volume",
"genesis plus gx psg channel 3 volume": "genesis plus gx - psg channel 3 volume",
"genesis plus gx md channel 0 volume": "genesis plus gx - md channel 0 volume",
"genesis plus gx md channel 1 volume": "genesis plus gx - md channel 1 volume",
"genesis plus gx md channel 2 volume": "genesis plus gx - md channel 2 volume",
"genesis plus gx md channel 3 volume": "genesis plus gx - md channel 3 volume",
"genesis plus gx md channel 4 volume": "genesis plus gx - md channel 4 volume",
"genesis plus gx md channel 5 volume": "genesis plus gx - md channel 5 volume",
"genesis plus gx sms fm channel 0 volume": "genesis plus gx - sms fm channel 0 volume",
"genesis plus gx sms fm channel 1 volume": "genesis plus gx - sms fm channel 1 volume",
"genesis plus gx sms fm channel 2 volume": "genesis plus gx - sms fm channel 2 volume",
"genesis plus gx sms fm channel 3 volume": "genesis plus gx - sms fm channel 3 volume",
"genesis plus gx sms fm channel 4 volume": "genesis plus gx - sms fm channel 4 volume",
"genesis plus gx sms fm channel 5 volume": "genesis plus gx - sms fm channel 5 volume",
"genesis plus gx sms fm channel 6 volume": "genesis plus gx - sms fm channel 6 volume",
"genesis plus gx sms fm channel 7 volume": "genesis plus gx - sms fm channel 7 volume",
"genesis plus gx sms fm channel 8 volume": "genesis plus gx - sms fm channel 8 volume",
"stella2014 stelladaptor analog sensitivity": "stella2014 - Sensibilidade do Analógico",
"stella2014 stelladaptor analog center": "stella2014 - Centro do Analógico",
"Download Game BIOS": "Carregando bios do videogame",
"Decompress Game BIOS": "Descompactando bios do videogame",
"1.0x (12.50Mhz)": "1.0x (12.50Mhz)",
"1.1x (13.75Mhz)": "1.1x (13.75Mhz)",
"1.2x (15.00Mhz)": "1.2x (15.00Mhz)",
"1.5x (18.75Mhz)": "1.5x (18.75Mhz)",
"1.6x (20.00Mhz)": "1.6x (20.00Mhz)",
"1.8x (22.50Mhz)": "1.8x (22.50Mhz)",
"2.0x (25.00Mhz)": "2.0x (25.00Mhz)",
"opera cpu overclock": "Overclock do cpu Opera",
"0RGB1555": "0RGB1555",
"RGB565": "RGB565",
"XRGB8888": "XRGB8888",
"opera vdlp pixel format": "Formato vdlp do pixel Opera",
"opera nvram version": "Versão da nvram do Opera",
"opera active devices": "Dispositivos Opera ativados",
"pcsx rearmed psxclock": "pcsx rearmed - psxclock",
"pcsx rearmed frameskip threshold": "pcsx rearmed - limite de pulo de quadros",
"pcsx rearmed frameskip interval": "pcsx rearmed - intervalo de pulo de quadros",
"pcsx rearmed input sensitivity": "pcsx rearmed - sensibilidade de entrada",
"pcsx rearmed gunconadjustx": "pcsx rearmed - gunconadjustx",
"pcsx rearmed gunconadjusty": "pcsx rearmed - gunconadjusty",
"pcsx rearmed gunconadjustratiox": "pcsx rearmed - gunconadjustratiox",
"pcsx rearmed gunconadjustratioy": "pcsx rearmed - gunconadjustratioy",
"Start Game": "Jogar"
}

**Comment by ethanaobrien** [comment]
@zmarteline The issue is the files encoding. Your file is ANSI, but UTF-8 is expected

**Comment by allancoding** [comment]
Worked for me:

**Comment by ethanaobrien** [comment]
Me too, and for him... it's the encoding

**Comment by zmarteline** [comment]
can you create the file? when I try to modify I gett an error:
y

**Comment by allancoding** [comment]
What file editor are you using?

**Comment by zmarteline** [comment]
Nevermind, fixed.
[pt-BR.json.txt](https://github.com/EmulatorJS/EmulatorJS/files/12327871/pt-BR.json.txt)

**Comment by zmarteline** [comment]
thanks guys.

**Comment by zmarteline** [comment]
> What file editor are you using?

Winscp internal editor

**Comment by zmarteline** [comment]
By the way, the latest attached file is ready for use... you can put in the repo. :)

**Comment by allancoding** [comment]
Ok, thanks

**Comment by allancoding** [comment]
@zmarteline It looks like alot of translations were removed?

**Comment by zmarteline** [comment]
all genesis, master system, 32x, Sega cd, Atari 2600, 3DO and PSX labels are here.
No missing label warnings.
[pt-BR.json.txt](https://github.com/EmulatorJS/EmulatorJS/files/12327906/pt-BR.json.txt)

Use this one, I revert back the label save state to english, it's more common here use it this way.

**Comment by zmarteline** [comment]
Captura
As you can see, no warnings related to Translations.

**Comment by allancoding** [comment]
@zmarteline It needs to have all the ones below because the translation function has not been run on some of the menus until you open them some like netplay are hidden but are still needed. So they will not show in the console but they are needed for them when you click on them:
```
{
    "Restart": "-Restart",
    "Pause": "-Pause",
    "Play": "-Play",
    "Save State": "-Save State",
    "Load State": "-Load State",
    "Control Settings": "-Control Settings",
    "Cheats": "-Cheats",
    "Cache Manager": "-Cache Manager",
    "Export Save File": "-Export Save File",
    "Import Save File": "-Import Save File",
    "Netplay": "-Netplay",
    "Mute": "-Mute",
    "Unmute": "-Unmute",
    "Settings": "-Settings",
    "Enter Fullscreen": "-Enter Fullscreen",
    "Exit Fullscreen": "-Exit Fullscreen",
    "Reset": "-Reset",
    "Clear": "-Clear",
    "Close": "-Close",
    "QUICK SAVE STATE": "-QUICK SAVE STATE",
    "QUICK LOAD STATE": "-QUICK LOAD STATE",
    "CHANGE STATE SLOT": "-CHANGE STATE SLOT",
    "FAST FORWARD": "-FAST FORWARD",
    "Player": "-Player",
    "Connected Gamepad": "-Connected Gamepad",
    "Gamepad": "-Gamepad",
    "Keyboard": "-Keyboard",
    "Set": "-Set",
    "Add Cheat": "-Add Cheat",
    "Create a Room": "-Create a Room",
    "Rooms": "-Rooms",
    "Start Game": "-Start Game",
    "Loading...": "-Loading...",
    "Download Game Core": "-Download Game Core",
    "Decompress Game Core": "-Decompress Game Core",
    "Download Game Data": "-Download Game Data",
    "Decompress Game Data": "-Decompress Game Data",
    "Shaders": "-Shaders",
    "Disabled": "-Disabled",
    "2xScaleHQ": "-2xScaleHQ",
    "4xScaleHQ": "-4xScaleHQ",
    "CRT easymode": "-CRT easymode",
    "CRT aperture": "-CRT aperture",
    "CRT geom": "-CRT geom",
    "CRT mattias": "-CRT mattias",
    "FPS": "-FPS",
    "show": "-show",
    "hide": "-hide",
    "Fast Forward Ratio": "-Fast Forward Ratio",
    "Fast Forward": "-Fast Forward",
    "Enabled": "-Enabled",
    "Save State Slot": "-Save State Slot",
    "Save State Location": "-Save State Location",
    "Download": "-Download",
    "Keep in Browser": "-Keep in Browser",
    "Auto": "-Auto",
    "NTSC": "-NTSC",
    "PAL": "-PAL",
    "Dendy": "-Dendy",
    "8:7 PAR": "-8:7 PAR",
    "4:3": "-4:3",
    "Low": "-Low",
    "High": "-High",
    "Very High": "-Very High",
    "None": "-None",
    "Player 1": "-Player 1",
    "Player 2": "-Player 2",
    "Both": "-Both",
    "SAVED STATE TO SLOT": "-SAVED STATE TO SLOT",
    "LOADED STATE FROM SLOT": "-LOADED STATE FROM SLOT",
    "SET SAVE STATE SLOT TO": "-SET SAVE STATE SLOT TO",
    "Network Error": "-Network Error",
    "Submit": "-Submit",
    "Description": "-Description",
    "Code": "-Code",
    "Add Cheat Code": "-Add Cheat Code",
    "Leave Room": "-Leave Room",
    "Password": "-Password",
    "Password (optional)": "-Password (optional)",
    "Max Players": "-Max Players",
    "Room Name": "-Room Name",
    "Join": "-Join",
    "Player Name": "-Player Name",
    "Set Player Name": "-Set Player Name",
    "Left Handed Mode": "-Left Handed Mode",
    "Virtual Gamepad": "-Virtual Gamepad",
    "Disk": "-Disk",
    "Press Keyboard": "-Press Keyboard",
    "INSERT COIN": "-INSERT COIN",
    "Remove": "-Remove",
    "SAVE LOADED FROM BROWSER": "-SAVE LOADED FROM BROWSER",
    "SAVE SAVED TO BROWSER": "-SAVE SAVED TO BROWSER",
    "Join the discord": "-Join the discord",
    "View on GitHub": "-View on GitHub",
    "Failed to start game": "-Failed to start game",
    "Download Game BIOS": "-Download Game BIOS",
    "Decompress Game BIOS": "-Decompress Game BIOS",
    "Download Game Parent": "-Download Game Parent",
    "Decompress Game Parent": "-Decompress Game Parent",
    "Download Game Patch": "-Download Game Patch",
    "Decompress Game Patch": "-Decompress Game Patch",
    "Download Game State": "-Download Game State",
    "Check console": "-Check console",
    "Error for site owner": "-Error for site owner",
    "EmulatorJS": "-EmulatorJS",
    "Clear All": "-Clear All",
    "Take Screenshot": "-Take Screenshot",
    "Quick Save": "-Quick Save",
    "Quick Load": "-Quick Load",
    "REWIND": "-REWIND",
    "Rewind Enabled (requires restart)": "-Rewind Enabled (requires restart)",
    "Rewind Granularity": "-Rewind Granularity",
    "Slow Motion Ratio": "-Slow Motion Ratio",
    "Slow Motion": "-Slow Motion",
    "Home": "-Home",
    "EmulatorJS License": "-EmulatorJS License",
    "RetroArch License": "-RetroArch License",
    "SLOW MOTION": "-SLOW MOTION"
}
```

**Comment by zmarteline** [comment]
Ok, I will add the missing ones from above.

**Comment by allancoding** [comment]
Just add the new ones below the SLOW MOTION

Thanks

**Comment by allancoding** [comment]
@zmarteline Or it might just be easier to reedit the current one:
```
{
    "Restart": "Reiniciar",
    "Pause": "Pausa",
    "Play": "Jogar",
    "Save State": "Estado salvo",
    "Load State": "Estado de carga",
    "Control Settings": "Configurações de controle",
    "Cheats": "Fraudes",
    "Cache Manager": "Gerenciador de Cache",
    "Export Save File": "Exportar Salvar Arquivo",
    "Import Save File": "Importar Salvar Arquivo",
    "Netplay": "Jogo de rede",
    "Mute": "Mudo",
    "Unmute": "Ativar som",
    "Settings": "Configurações",
    "Enter Fullscreen": "Entrar em tela cheia",
    "Exit Fullscreen": "Sair da tela cheia",
    "Reset": "Reiniciar",
    "Clear": "Claro",
    "Close": "Fechar",
    "QUICK SAVE STATE": "SALVAR ESTADO RÁPIDO",
    "QUICK LOAD STATE": "ESTADO DE CARGA RÁPIDA",
    "CHANGE STATE SLOT": "MUDAR ESPAÇO DE ESTADO",
    "FAST FORWARD": "AVANÇO RÁPIDO",
    "Player": "Jogador",
    "Connected Gamepad": "Gamepad conectado",
    "Gamepad": "Controle",
    "Keyboard": "Teclado",
    "Set": "Definir",
    "Add Cheat": "Adicionar trapaça",
    "Create a Room": "Criar uma sala",
    "Rooms": "quartos",
    "Start Game": "Começar o jogo",
    "Loading...": "Carregando...",
    "Download Game Core": "Baixe o Núcleo do Jogo",
    "Decompress Game Core": "Descomprimir Núcleo do Jogo",
    "Download Game Data": "Baixar dados do jogo",
    "Decompress Game Data": "Descomprimir Dados do Jogo",
    "Shaders": "Shaders",
    "Disabled": "Desabilitado",
    "2xScaleHQ": "2xScaleHQ",
    "4xScaleHQ": "4xScaleHQ",
    "CRT easymode": "CRT modo fácil",
    "CRT aperture": "abertura CRT",
    "CRT geom": "geom CRT",
    "CRT mattias": "CRT Mattias",
    "FPS": "FPS",
    "show": "mostrar",
    "hide": "esconder",
    "Fast Forward Ratio": "Taxa de Avanço Rápido",
    "Fast Forward": "Avanço rápido",
    "Enabled": "Habilitado",
    "Save State Slot": "Salvar Slot de Estado",
    "Save State Location": "Salvar localização do estado",
    "Download": "Download",
    "Keep in Browser": "Manter no navegador",
    "Auto": "Auto",
    "NTSC": "NTSC",
    "PAL": "AMIGO",
    "Dendy": "Dendy",
    "8:7 PAR": "8:7 PAR",
    "4:3": "4:3",
    "Low": "Baixo",
    "High": "Alto",
    "Very High": "Muito alto",
    "None": "Nenhum",
    "Player 1": "Jogador 1",
    "Player 2": "Jogador 2",
    "Both": "Ambos",
    "SAVED STATE TO SLOT": "ESTADO SALVO NO ESPAÇO",
    "LOADED STATE FROM SLOT": "ESTADO CARREGADO DO SLOT",
    "SET SAVE STATE SLOT TO": "CONFIGURAR SALVAR ESTADO DE SALVAR PARA",
    "Network Error": "Erro de rede",
    "Submit": "Enviar",
    "Description": "Descrição",
    "Code": "Código",
    "Add Cheat Code": "Adicionar código de trapaça",
    "Leave Room": "Sair da sala",
    "Password": "Senha",
    "Password (optional)": "Senha (opcional)",
    "Max Players": "Máximo de jogadores",
    "Room Name": "Nome da sala",
    "Join": "Juntar",
    "Player Name": "Nome do jogador",
    "Set Player Name": "Definir nome do jogador",
    "Left Handed Mode": "Modo canhoto",
    "Virtual Gamepad": "Gamepad virtual",
    "Disk": "Disco",
    "Press Keyboard": "Pressione Teclado",
    "INSERT COIN": "INSIRA MOEDA",
    "Remove": "Remover",
    "SAVE LOADED FROM BROWSER": "SALVAR CARREGADO DO NAVEGADOR",
    "SAVE SAVED TO BROWSER": "SALVAR SALVO NO NAVEGADOR",
    "Join the discord": "Junte-se à discórdia",
    "View on GitHub": "Ver no GitHub",
    "Failed to start game": "Falha ao iniciar o jogo",
    "Download Game BIOS": "Baixar BIOS do jogo",
    "Decompress Game BIOS": "Descompactar o BIOS do jogo",
    "Download Game Parent": "Baixe o pai do jogo",
    "Decompress Game Parent": "Descompactar o pai do jogo",
    "Download Game Patch": "Baixe o patch do jogo",
    "Decompress Game Patch": "Descompactar patch do jogo",
    "Download Game State": "Baixar estado do jogo",
    "Check console": "Verifique o console",
    "Error for site owner": "Erro para o proprietário do site",
    "EmulatorJS": "EmuladorJS",
    "Clear All": "Limpar tudo",
    "Take Screenshot": "Tirar captura de tela",
    "Quick Save": "Salvamento rapido",
    "Quick Load": "Carga rápida",
    "REWIND": "REBOBINAR",
    "Rewind Enabled (requires restart)": "Retrocesso ativado (requer reinicialização)",
    "Rewind Granularity": "Rebobinar granularidade",
    "Slow Motion Ratio": "Taxa de câmera lenta",
    "Slow Motion": "Câmera lenta",
    "Home": "Lar",
    "EmulatorJS License": "Licença EmulatorJS",
    "RetroArch License": "Licença RetroArch",
    "SLOW MOTION": "CÂMERA LENTA"
}
```

**Comment by zmarteline** [comment]
Almost done, so, can you let me know what is Dendy  and Game Parent, so I don't misstranslate?

**Comment by allancoding** [comment]
I think Dendy is a name and Game Parent is the top most element or something.

**Comment by zmarteline** [comment]
[pt-BR.json.txt](https://github.com/EmulatorJS/EmulatorJS/files/12328052/pt-BR.json.txt)
Ok, I Added these ones to the end of my file, sorry I did not use yours, I already had started...

    "Auto": "Auto",
    "NTSC": "NTSC",
    "PAL": "PAL",
    "Dendy": "Dendy",
    "8:7 PAR": "8:7 PAR",
    "4:3": "4:3",
    "Low": "Baixo",
    "High": "Alto",
    "Very High": "Muito alto",
    "None": "Nenhum",
    "Player 1": "Jogador 1",
    "Player 2": "Jogador 2",
    "Both": "Ambos",
    "SAVED STATE TO SLOT": "SAVE STATE ARMAZENDO NO SLOT",
    "LOADED STATE FROM SLOT": "SAVE STATE CARREGADO DO SLOT",
    "SET SAVE STATE SLOT TO": "SAVE STATE DEFINIDO PARA SLOT",
    "Network Error": "Erro de rede",
    "Submit": "Enviar",
    "Description": "Descrição",
    "Code": "Código",
    "Add Cheat Code": "Adicionar trapaça",
    "Leave Room": "Sair da sala",
    "Password": "Senha",
    "Password (optional)": "Senha (opcional)",
    "Max Players": "-Max de Jogadores",
    "Room Name": "Nome da Sala",
    "Join": "Entrar",
    "Player Name": "Nome do Jogador",
    "Set Player Name": "Definir nome do Jogador",
    "Disk": "Disco",
    "Press Keyboard": "Pressione uma tecla",
    "INSERT COIN": "Insira uma ficha",
    "Remove": "Remover",
    "SAVE LOADED FROM BROWSER": "SAVE STATE CARREGADO DO BROWSER",
    "SAVE SAVED TO BROWSER": "SAVE STATE  ARMAZENADO NO BROWSER",
    "Join the discord": "Participar do discord",
    "View on GitHub": "Ver no GitHub",
    "Failed to start game": "Falha ao iniciar o jogo",
    "Download Game Parent": "Carregando arquivo principal do jogo",
    "Decompress Game Parent": "Descompactando arquivo principal do jogo",
    "Download Game Patch": "Carregando Patch do jogo",
    "Decompress Game Patch": "Descompactando Patch do Jogo",
    "Download Game State": "Carregando Save State",
    "Check console": "Verificar videogame",
    "Error for site owner": "Erro para proprietário do site",
    "EmulatorJS": "EmulatorJS",
    "Clear All": "Limpar todos",
    "Take Screenshot": "Capturar tela",
    "Quick Save": "Salvar rapidamente",
    "Quick Load": "Carregar Rapidmente",
    "Home": "Ínicio",
    "EmulatorJS License": "Licença do EmulatorJS",
    "RetroArch License": "Licença do RetroArch",

Can you please check if I miss something? And again, sorry for the mess.

**Comment by allancoding** [comment]
Ok thanks, that looks good I will add it later today.

**Comment by zmarteline** [comment]
By the way, I loved the fact that netplay labels was in there... It give me hope that it will come back soon.... 😄

**Comment by allancoding** [comment]
Netplay is being worked on and I can't wait either.
I updated `pt-BR.json` in #612

**Pull request merged**
