### PR TITLE
Fix build error in npm.yml

### PR DESCRIPTION
**Pull request by allancoding**
Needs a package-lock.json

### CODE REVIEW

**Comment by cohenerickson** [comment]
You may also need to change the publish command to be `npm publish --access public`. When publishing packages under an organization name the visibility defaults to private instead of public.

**Comment by allancoding** [comment]
Thanks

**Review by ethanaobrien — APPROVED** [review]

**Comment by cohenerickson** [comment]
Is it possible to also get the game cores published to NPM or are there limits on the file sizes?

**Comment by allancoding** [comment]
Right now all the cores are 200+ mb don't want to push this the the main repo. but we could make another npm @emulatorjs/cores

**Comment by ethanaobrien** [comment]
And to add, the 200mb of core files will only get bigger

**Comment by michael-j-green** [comment]
Could the cores be deployed separately? Perhaps on a per platform basis rather than one mega package?

Alternative is a stub package that when executed/installed/etc downloads the files from the CDN based on the package version.

**Comment by allancoding** [comment]
yes that would be nice I will look into adding that to the stable script. I might do it by company so like nintendo cores, then sony cores, etc

**Pull request merged**
