### PR TITLE
WonderSwan, ColecoVision support

### PR DESCRIPTION
**Pull request by n-at**
Includes WASM build of https://github.com/drhelius/Gearcoleco (it builds without any modifications) and https://github.com/libretro/beetle-wswan-libretro (with usual Makefile modification for beetle cores).
Control scheme and virtual gamepads included.

(also tried to build PC-FX core from https://github.com/libretro/beetle-pcfx-libretro, but it's not working)

### CODE REVIEW

**Comment by ethanaobrien** [comment]
Thank you! (Sorry I haven't been working much, I got sick recently and feel too weak to move)

I've created https://github.com/EmulatorJS/beetle-wswan-libretro (and https://github.com/EmulatorJS/Gearcoleco) so you can submit your patches and add it to the build script 

Would you mind providing the errors produced by PC-FX. I think I remember looking at that one and I think `HAVE_THREADS = 0` needs to be disabled for emscripten

**Comment by n-at** [comment]
This is my build of mednafen_pcfx: https://github.com/n-at/EmulatorJS/blob/feature-pcfx-wswan/data/cores/mednafen_pcfx-wasm.data - after loading ROM and BIOS shows just black screen and loads CPU. There is no errors in console output:

```
(2) ['-v', '/Lunatic Dawn-0.cue']
emulator.js:1001 Built for EmulatorJS Version 4.0.6
emulator.js:1001 Download a copy from https://github.com/EmulatorJS/EmulatorJS
emulator.js:1001 View the licence here: https://github.com/EmulatorJS/EmulatorJS/blob/main/LICENSE
emulator.js:1006 [INFO] RetroArch 1.16.0 (Git e08707d3f1)
emulator.js:1006 [INFO] === Build =======================================
emulator.js:1006 [INFO] Capabilities: 
emulator.js:1006 [INFO] Version: 1.16.0
emulator.js:1006 [INFO] Git: e08707d3f1
emulator.js:1006 [INFO] Built: Aug 31 2023
emulator.js:1006 [INFO] =================================================
emulator.js:1006 [INFO] [Input]: Found input driver: "emulatorjs".
emulator.js:1006 [INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
emulator.js:1006 [INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
emulator.js:1006 [INFO] [Environ]: SET_CONTROLLER_INFO.
emulator.js:1006 [INFO] [Environ]: GET_VFS_INTERFACE. Core requested version >= V2, providing V3.
emulator.js:1006 [INFO] [Overrides]: Redirecting save file to "/data/saves/Lunatic Dawn-0.srm".
emulator.js:1006 [INFO] [Overrides]: Redirecting save state to "/home/web_user/retroarch/userdata/states/Lunatic Dawn-0.state".
emulator.js:1006 [INFO] [Environ]: GET_LOG_INTERFACE.
emulator.js:1006 [INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
emulator.js:1006 [INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
emulator.js:1006 [WARN] [Environ]: SYSTEM DIR is empty, assume CONTENT DIR /Lunatic Dawn-0.cue
emulator.js:1006 [INFO] [Environ]: SYSTEM_DIRECTORY: "".
emulator.js:1006 [INFO] [Environ]: GET_SAVE_DIRECTORY.
emulator.js:1006 [INFO] [Environ]: GET_PERF_INTERFACE.
emulator.js:1006 [INFO] [Environ]: PERFORMANCE_LEVEL: 15.
emulator.js:1006 [INFO] [Content]: Content loading skipped. Implementation will load it on its own.
emulator.js:1006 [INFO] [Environ]: SET_INPUT_DESCRIPTORS:
emulator.js:1006 [INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
emulator.js:1006 [libretro INFO] Loading SBI file "/Lunatic Dawn-0.sbi"...
```

BIOS is `pcfx.rom` from here: https://github.com/Abdess/retroarch_system

**Comment by ethanaobrien** [comment]
Hmm, that's the entire log? Is the page still responsive, or does it freeze?


You applied the patch here too, right?


Also, did you try setting both `HAVE_THREADS` and possibly `NO_GCC` to `0` for emscripten?

**Comment by n-at** [comment]
Yes, that helped. Thank you. (will make PR with PC-FX)

**Comment by ethanaobrien** [comment]
Awesome, thank you

I created a branch here - https://github.com/EmulatorJS/beetle-pcfx-libretro

**Pull request merged**
