### PR TITLE
rewind

### PR DESCRIPTION
**Pull request by n-at**
Adds rewind control. Disabled by default - not all cores may support rewind and it uses additional memory (may be problem on "heavy" platforms like psx).
Introduces new option `EJS_rewindEnabled`.

### CODE REVIEW

**Comment by ethanaobrien** [comment]
Hey @n-at and thank you so much. I do have one question. Instead of having the site owner needing to enable Rewind, how about adding the option `Rewind (requires restart)` to the settings menu? Since Rewind (as you mentioned) may impact performance. 


Then just read this option from the saved settings and setup the emulator based on that.

**Comment by n-at** [comment]
Yes, that's will be better. Added rewind control in settings menu.

**Comment by ethanaobrien** [comment]
image
Is it safe to do this? Since rewind requires restart - shouldnt this variable only be set on load?

Other than that it looks good! Thank you so much!

**Comment by n-at** [comment]
Yes, it's not needed. Removed that code.

**Comment by ethanaobrien** [comment]
Awesome, thank you so much! I'll merge this right after I get the cores compiled, and thank you so much!

**Comment by allancoding** [comment]
@n-at Thank you so much! In the future when adding a new option like  `EJS_rewindEnabled` add it to the loader.js
It will make adding documentation a lot easier. We didn't end up using that option, but i'm just telling you for future reference.

Thanks!

**Pull request merged**
