### PR TITLE
Fix game style for index.html

### PR DESCRIPTION
**Pull request by allancoding**
Fix game style for `index.html`

### CODE REVIEW

**Comment by ethanaobrien** [comment]
@allancoding Could you check and make sure this works. It isnt loading for me.

**Comment by allancoding** [comment]
image
It is working for me.

**Comment by ethanaobrien** [comment]
@allancoding

I think it might be with the select game core screen (I didnt use a real game because I didnt have any on hand, but it should have still loaded)

https://user-images.githubusercontent.com/77750390/155427475-23307858-6dc9-4999-b740-107edbdecc34.mp4

**Comment by allancoding** [comment]
I changed some of the code but if you select a rom it will work. I will send you one to test.

**Comment by ethanaobrien** [comment]
The problem is when the file is zipped. Can you look at this?

Edit: I fixed this

**Pull request merged**
