### PR TITLE
Special Edition

### PR DESCRIPTION
**Pull request by nenge123**
However, you may need to manually replace simplified Chinese with your language

### CODE REVIEW

**Comment by ethanaobrien** [comment]
This is cool. From what I see it adds explanation to all of the files.

What does the `index.php` file do?

Does github pages support php?

**Comment by nenge123** [comment]
you write some javascript code replace this php code.

**Comment by nenge123** [comment]
if you can visit it
php files is do that...

you can make two html (index.html,player.html)and some javascript replace that.

https://nenge.net/emulator/app/emujs/


i add the can load/download *.srm save files

can read last state saves when i  open this game (ps1 not active)

custom to upload  my game files .not need to the server have this game.

**Comment by birdinforest** [comment]
Hi @nenge123 thanks for your pull request. I am thinking about how to customize the game save&load feature and to customize the control pad UI. Your pull request makes it possible.

Would you like to give me some advice about how to understand and modify the file `emulator.js`? I guess it is a emscriten generated file, thus it is not human readable. Is there any way or any tool helping us to understand its functional logic?

Unfortunatelly I can not find your contat. It will be appreciated if you could leave your email, or wechat here, or if you could contact me directly. My email: birdinforest@gmail.com WeChat: birdinforest. By the way I speak Chinese.

Sorry @ethanaobrien to leave the command which might be irrelative to the topic.

**Pull request closed without merging**
