### PR TITLE
Formatting Refinements

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
Please check the **[Preview]**.

#### Changes

- Simplified formatting
- Adjusted supported systems style

[Preview]: https://github.com/ElectronicsArchiver/emulatorjs

### CODE REVIEW

**Comment by ethanaobrien** [comment]
Looks good, on thing. Could you also center the company title that is right above the systems made by that company

**Comment by ethanaobrien** [comment]
Thank you!

**Comment by ethanaobrien** [comment]
Hey @ElectronicsArchiver could you create a pull request and add [this](https://github.com/Ramaerel/emulatorjs-GameLibrary) to the readme? Say something like "gamelibrary utility"

Thanks! Youre so much better at formatting than I am

**Comment by ElectronicsArchiver** [comment]
You just want it linked in your README?

**Pull request merged**
