### PR TITLE
Added Contributors File

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
<br>
<br>

*Please check the **[Preview]**.*

<br>
<br>

### Changes

- Added contributors file
- Added quicklink

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/emulatorjs

### CODE REVIEW

**Comment by ethanaobrien** [comment]
it looks like you have the wrong link to my profile, Could you check this?

**Comment by ElectronicsArchiver** [comment]
Fixed it.

Sorry reused the basic layout from another 
authors file I made and forgot to change it~

**Comment by ethanaobrien** [comment]
Its all good

**Comment by ethanaobrien** [comment]
Awesome, thank you. I am now merging

**Pull request merged**
