### PR TITLE
Control scheme, buttons and virtual gamepads

### PR DESCRIPTION
**Pull request by n-at**
Added ability to explicitly define control scheme for controls menu and virtual gamepad. Introduces new option `EJS_controlScheme`. Default behaviour (when option is undefined) not changed (core name will be used).

Added control buttons for gba, vb, 3do, atari2600, atari7800, lynx, jaguar, updated for n64.

Added virtual gamepads for atari2600, atari7800, lynx, jaguar, vb, 3do and updated for nes, segaSaturn.

nes
nes

segaSaturn
segaSaturn

vb
vb

3do
3do

atari2600
atari2600

atari7800
atari7800

lynx
lynx

jaguar
jaguar

### CODE REVIEW

**Comment by ethanaobrien** [comment]
This is a really good idea. Thank you for your contribution! I left a comment on one line, hopefully you can see it. Let me know if you cant

**Comment by n-at** [comment]
No, I dont't see the comment. Can you post here link to that line?

**Comment by ethanaobrien** [comment]
Yeah,

Line 1753 of emulator.js
(`        if (this.config.controlScheme) {`)

Could you check and make sure the type of `this.config.controlScheme` is a string

**Comment by n-at** [comment]
Ok, check added.

**Comment by ethanaobrien** [comment]
Awesome, thank you so much for your contributions!

**Pull request merged**
