### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by ethanaobrien**
I will merge this once I get the results back from a DMCA takedown request

### CODE REVIEW

**Comment by allancoding** [comment]
What DMCA takedown request?

**Comment by ethanaobrien** [comment]
I submited a request against [this](https://github.com/Kooyle/DKA.GitHub.io) repository (which is a clone of [this](https://github.com/nenge123/emulatorjs/) repository)

**Comment by allancoding** [comment]
What did they do?

**Comment by allancoding** [comment]
Is my https://github.com/allancoding/emulatorjs-allancoding/tree/main against the license. I have added some jquery to make a background image and some other minor things is that ok?

**Comment by ethanaobrien** [comment]
I saw your repository. I let it slide since it is a branch of this main repository (while the other one was a download and re-upload), but technically yes, since the licence also says to state changes (Thats not too hard) so if you could add that that'd be awesome

**Comment by allancoding** [comment]
Ok I will do that. But what about this one? https://github.com/allancoding/emulatorjs-maker

**Comment by ethanaobrien** [comment]
As long as none of the files are modified, its all fine (although you might want to state that there are no modifications, its good practice to get used to following the license even when it seems a little crazy because other people out there are crazy and theyre gonna get onto you for crazy small things)

**Comment by allancoding** [comment]
All I added was this:
````
$(document).ready(function(){
    $(".ejs--73f9b4e94a7a1fe74e11107d5ab2ef").attr("id","start");
    $(".ejs--cbcfe0a1421cadac9a04c81d6431d6").attr("id","loding");
    $(".ejs--71527b6509aa48afce3ce1a11c02f0").attr("id","naming");
    $(".ejs--057800d021995e1347ec07cb748672").addClass("backg");
    $("#loding").attr("hidden","");
    $("#loding").hide();
    $("#start").on('touchstart click', function() {
    $(".ejs--057800d021995e1347ec07cb748672").removeClass("backg");
    $("#loding").show();
    $("#loding").removeAttr("hidden");
    $("div").remove(".ejs--f3a1903d935f6cf720d4a0498db62a");
    setTimeout(
  function() 
  {
    $("div").remove(".ejs--cbcfe0a1421cadac9a04c81d6431d6");
  }, 4500);
});
});
````
Witch sets that background image in labels phone tap (on start) and  remove the add loader after 4.5 seconds.
Funny thing is I was looking for a emulator and I found https://neptunjs.xyz/ and I tired to remove the ads but they have all the code encrypted. Then I found EmulatorJS and removed the add. Then I found this repository!

**Comment by ethanaobrien** [comment]
yep! I mean Im not going to submit a takedown request if you dont primarily because its a branch of the main repository and you can view the differences that way but I would suggest it

**Comment by allancoding** [comment]
I updated my repositories!

**Comment by ethanaobrien** [comment]
Thank you!

**Pull request merged**
