### PR TITLE
Add button gamepad naming

### PR DESCRIPTION
**Pull request by allancoding**
This should add button naming for gamepad button 1, 2 etc.
Finishes #635 
@zmarteline Can you test this?

### CODE REVIEW

**Comment by allancoding** [comment]
@ethanaobrien do you have a controller you can test this with?

**Comment by ethanaobrien** [comment]
Yeah, can you host this somewhere

**Comment by allancoding** [comment]
https://allancoding-emulatorjs.netlify.app/

**Comment by zmarteline** [comment]
Sorry, I just wake up... I will test now!

**Comment by zmarteline** [comment]
Captura de tela 2023-08-26 181631
tested using your link... It works! I will upload to check translations...

**Comment by zmarteline** [comment]
It's pefect! Great job!
final

**Comment by allancoding** [comment]
Ok thanks

**Pull request merged**
